services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - caddy
  ta1:
    image: oidfed/lighthouse:main
    restart: unless-stopped
    volumes:
      - ./ta1/config.yaml:/config.yaml:ro
      - ./ta1/data:/data
    networks:
      - caddy

  ta2:
    image: oidfed/lighthouse:main
    restart: unless-stopped
    volumes:
      - ./ta2/config.yaml:/config.yaml:ro
      - ./ta2/data:/data
    networks:
      - caddy
  
  tmi-sirtfi:
    image: oidfed/lighthouse:main
    restart: unless-stopped
    volumes:
      - ./tmi-sirtfi/config.yaml:/config.yaml:ro
      - ./tmi-sirtfi/data:/data
    networks:
      - caddy

  rp:
    image: oidfed/offa:main
    restart: unless-stopped
    volumes:
      - ./rp/config.yaml:/config.yaml:ro
      - ./rp/data:/data
    networks:
      - caddy

  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      - caddy

  rp-expl:
    image: ddgu/fedservice:latest
    restart: unless-stopped
    init: true
    volumes:
      - ./rp-expl/rp/rp-expl:/conf
    environment:
      - ENTITY_TYPE=rp
      - ENTITY_NAME=rp-expl
    networks:
      - caddy

networks:
  caddy:
    external: true
