server:
  port: 7672
signing:
  alg: ES256
  key_dir: "/data/signing"
federation_data:
  entity_id: "https://ta2.g100.aarc3-pilots.vm.fedcloud.eu"
  federation_entity_metadata:
    display_name: "AARC G100 Pilot TA [G100.2]"
    organization_name: "AARC G100 Pilot"
  metadata_policy_file: "/data/metadata_policy.json"
  trust_mark_issuers:
    "https://refeds.org/sirtfi":
      - https://tmi-sirtfi.g100.aarc3-pilots.vm.fedcloud.eu
    "https://refeds.org/sirtfi2":
      - https://tmi-sirtfi.g100.aarc3-pilots.vm.fedcloud.eu
storage:
  backend: badger
  data_dir: "/data/storage"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  enroll:
    path: "/enroll"
    checker:
      type: multiple_or
      config:
        - type: entity_id
          config:
            entity_ids:
              - https://tmi-sirtfi.g100.aarc3-pilots.vm.fedcloud.eu
        - type: multiple_and
          config:
            - type: authority_hints
              config:
                entity_id: https://ta2.g100.aarc3-pilots.vm.fedcloud.eu
            - type: entity_id
              config:
                entity_ids:
                  - https://rp.g100.aarc3-pilots.vm.fedcloud.eu
                  - https://op.g100.aarc3-pilots.vm.fedcloud.eu
                  - https://rp-expl.g100.aarc3-pilots.vm.fedcloud.eu
            - type: multiple_or
              config:
              - type: trust_mark
                config:
                  trust_mark_type: https://refeds.org/sirtfi
                  trust_anchors:
                    - entity_id: https://ta2.g100.aarc3-pilots.vm.fedcloud.eu
              - type: trust_mark
                config:
                  trust_mark_type: https://refeds.org/sirtfi2
                  trust_anchors:
                    - entity_id: https://ta2.g100.aarc3-pilots.vm.fedcloud.eu
