server:

logging:
  access:
    stderr: true
  internal:
    level: info
    stderr: true

sessions:
  ttl: 3600
  cookie_domain: g100.aarc3-pilots.vm.fedcloud.eu

auth:
  - domain: whoami.g100.aarc3-pilots.vm.fedcloud.eu
    require:
      groups: users

federation:
  entity_id: https://rp.g100.aarc3-pilots.vm.fedcloud.eu
  trust_anchors:
    - entity_id: https://ta1.g100.aarc3-pilots.vm.fedcloud.eu
    - entity_id: https://ta2.g100.aarc3-pilots.vm.fedcloud.eu
  authority_hints:
    - https://ta1.g100.aarc3-pilots.vm.fedcloud.eu
    - https://ta2.g100.aarc3-pilots.vm.fedcloud.eu
  logo_uri: https://rp.g100.aarc3-pilots.vm.fedcloud.eu/static/img/offa-text.svg
  organization_name: "AARC G100 Pilot"
  use_resolve_endpoint: true
  use_entity_collection_endpoint: true
  trust_marks:
    - trust_mark_type: https://refeds.org/sirtfi2
      trust_mark_issuer: https://tmi-sirtfi.g100.aarc3-pilots.vm.fedcloud.eu
      refresh: true
      min_lifetime: 300
      refresh_grace_period: 7200
    - trust_mark_type: https://refeds.org/sirtfi
      trust_mark_issuer: https://tmi-sirtfi.g100.aarc3-pilots.vm.fedcloud.eu
      refresh: true
      min_lifetime: 300
      refresh_grace_period: 7200

signing:
  key_storage: /data

debug_auth: true
